/*
 New BSD License <http://creativecommons.org/licenses/BSD/>
 Public Domain
 @author Benjamin Arthur Lupton <contact@balupton.com>
 @author James Padolsey <https://gist.github.com/527683>
 Public Domain
 @author Benjamin Arthur Lupton <contact@balupton.com>
 New BSD License <http://creativecommons.org/licenses/BSD/>
*/
jQuery.easing.jswing=jQuery.easing.swing;
jQuery.extend(jQuery.easing,{def:"easeOutQuad",swing:function(e,b,d,c,g){return jQuery.easing[jQuery.easing.def](e,b,d,c,g)},easeInQuad:function(e,b,d,c,g){return c*(b/=g)*b+d},easeOutQuad:function(e,b,d,c,g){return-c*(b/=g)*(b-2)+d},easeInOutQuad:function(e,b,d,c,g){return(b/=g/2)<1?c/2*b*b+d:-c/2*(--b*(b-2)-1)+d},easeInCubic:function(e,b,d,c,g){return c*(b/=g)*b*b+d},easeOutCubic:function(e,b,d,c,g){return c*((b=b/g-1)*b*b+1)+d},easeInOutCubic:function(e,b,d,c,g){return(b/=g/2)<1?c/2*b*b*b+d:c/
2*((b-=2)*b*b+2)+d},easeInQuart:function(e,b,d,c,g){return c*(b/=g)*b*b*b+d},easeOutQuart:function(e,b,d,c,g){return-c*((b=b/g-1)*b*b*b-1)+d},easeInOutQuart:function(e,b,d,c,g){return(b/=g/2)<1?c/2*b*b*b*b+d:-c/2*((b-=2)*b*b*b-2)+d},easeInQuint:function(e,b,d,c,g){return c*(b/=g)*b*b*b*b+d},easeOutQuint:function(e,b,d,c,g){return c*((b=b/g-1)*b*b*b*b+1)+d},easeInOutQuint:function(e,b,d,c,g){return(b/=g/2)<1?c/2*b*b*b*b*b+d:c/2*((b-=2)*b*b*b*b+2)+d},easeInSine:function(e,b,d,c,g){return-c*Math.cos(b/
g*(Math.PI/2))+c+d},easeOutSine:function(e,b,d,c,g){return c*Math.sin(b/g*(Math.PI/2))+d},easeInOutSine:function(e,b,d,c,g){return-c/2*(Math.cos(Math.PI*b/g)-1)+d},easeInExpo:function(e,b,d,c,g){return b==0?d:c*Math.pow(2,10*(b/g-1))+d},easeOutExpo:function(e,b,d,c,g){return b==g?d+c:c*(-Math.pow(2,-10*b/g)+1)+d},easeInOutExpo:function(e,b,d,c,g){return b==0?d:b==g?d+c:(b/=g/2)<1?c/2*Math.pow(2,10*(b-1))+d:c/2*(-Math.pow(2,-10*--b)+2)+d},easeInCirc:function(e,b,d,c,g){return-c*(Math.sqrt(1-(b/=g)*
b)-1)+d},easeOutCirc:function(e,b,d,c,g){return c*Math.sqrt(1-(b=b/g-1)*b)+d},easeInOutCirc:function(e,b,d,c,g){return(b/=g/2)<1?-c/2*(Math.sqrt(1-b*b)-1)+d:c/2*(Math.sqrt(1-(b-=2)*b)+1)+d},easeInElastic:function(e,b,d,c,g){var e=1.70158,j=0,k=c;if(b==0)return d;if((b/=g)==1)return d+c;j||(j=g*0.3);k<Math.abs(c)?(k=c,e=j/4):e=j/(2*Math.PI)*Math.asin(c/k);return-(k*Math.pow(2,10*(b-=1))*Math.sin((b*g-e)*2*Math.PI/j))+d},easeOutElastic:function(e,b,d,c,g){var e=1.70158,j=0,k=c;if(b==0)return d;if((b/=
g)==1)return d+c;j||(j=g*0.3);k<Math.abs(c)?(k=c,e=j/4):e=j/(2*Math.PI)*Math.asin(c/k);return k*Math.pow(2,-10*b)*Math.sin((b*g-e)*2*Math.PI/j)+c+d},easeInOutElastic:function(e,b,d,c,g){var e=1.70158,j=0,k=c;if(b==0)return d;if((b/=g/2)==2)return d+c;j||(j=g*0.3*1.5);k<Math.abs(c)?(k=c,e=j/4):e=j/(2*Math.PI)*Math.asin(c/k);return b<1?-0.5*k*Math.pow(2,10*(b-=1))*Math.sin((b*g-e)*2*Math.PI/j)+d:k*Math.pow(2,-10*(b-=1))*Math.sin((b*g-e)*2*Math.PI/j)*0.5+c+d},easeInBack:function(e,b,d,c,g,j){j==void 0&&
(j=1.70158);return c*(b/=g)*b*((j+1)*b-j)+d},easeOutBack:function(e,b,d,c,g,j){j==void 0&&(j=1.70158);return c*((b=b/g-1)*b*((j+1)*b+j)+1)+d},easeInOutBack:function(e,b,d,c,g,j){j==void 0&&(j=1.70158);return(b/=g/2)<1?c/2*b*b*(((j*=1.525)+1)*b-j)+d:c/2*((b-=2)*b*(((j*=1.525)+1)*b+j)+2)+d},easeInBounce:function(e,b,d,c,g){return c-jQuery.easing.easeOutBounce(e,g-b,0,c,g)+d},easeOutBounce:function(e,b,d,c,g){return(b/=g)<1/2.75?c*7.5625*b*b+d:b<2/2.75?c*(7.5625*(b-=1.5/2.75)*b+0.75)+d:b<2.5/2.75?c*
(7.5625*(b-=2.25/2.75)*b+0.9375)+d:c*(7.5625*(b-=2.625/2.75)*b+0.984375)+d},easeInOutBounce:function(e,b,d,c,g){return b<g/2?jQuery.easing.easeInBounce(e,b*2,0,c,g)*0.5+d:jQuery.easing.easeOutBounce(e,b*2-g,0,c,g)*0.5+c*0.5+d}});
(function(e,b){var d=e.History=e.History||{},c=e.jQuery;if(typeof d.Adapter!=="undefined")throw Error("History.js Adapter has already been loaded...");d.Adapter={bind:function(b,d,e){c(b).bind(d,e)},trigger:function(b,d,e){c(b).trigger(d,e)},extractEventData:function(c,d,e){return d&&d.originalEvent&&d.originalEvent[c]||e&&e[c]||b},onDomLoad:function(b){c(b)}};typeof d.init!=="undefined"&&d.init()})(window);
(function(e,b){var d=e.console||b,c=e.document,g=e.navigator,j=e.sessionStorage||false,k=e.setTimeout,o=e.clearTimeout,q=e.setInterval,p=e.clearInterval,m=e.JSON,i=e.alert,a=e.History=e.History||{},l=e.history;m.stringify=m.stringify||m.encode;m.parse=m.parse||m.decode;if(typeof a.init!=="undefined")throw Error("History.js Core has already been loaded...");a.init=function(){if(typeof a.Adapter==="undefined")return false;typeof a.initCore!=="undefined"&&a.initCore();typeof a.initHtml4!=="undefined"&&
a.initHtml4();return true};a.initCore=function(){if(typeof a.initCore.initialized!=="undefined")return false;else a.initCore.initialized=true;a.options=a.options||{};a.options.hashChangeInterval=a.options.hashChangeInterval||100;a.options.safariPollInterval=a.options.safariPollInterval||500;a.options.doubleCheckInterval=a.options.doubleCheckInterval||500;a.options.storeInterval=a.options.storeInterval||1E3;a.options.busyDelay=a.options.busyDelay||250;a.options.debug=a.options.debug||false;a.options.initialTitle=
a.options.initialTitle||c.title;a.intervalList=[];a.clearAllIntervals=function(){var h,f=a.intervalList;if(typeof f!=="undefined"&&f!==null){for(h=0;h<f.length;h++)p(f[h]);a.intervalList=null}};a.debug=function(){a.options.debug&&a.log.apply(a,arguments)};a.log=function(){var a=!(typeof d==="undefined"||typeof d.log==="undefined"||typeof d.log.apply==="undefined"),f=c.getElementById("log"),b,g,e,l;a?(g=Array.prototype.slice.call(arguments),b=g.shift(),typeof d.debug!=="undefined"?d.debug.apply(d,
[b,g]):d.log.apply(d,[b,g])):b="\n"+arguments[0]+"\n";for(g=1,e=arguments.length;g<e;++g){l=arguments[g];if(typeof l==="object"&&typeof m!=="undefined")try{l=m.stringify(l)}catch(j){}b+="\n"+l+"\n"}f?(f.value+=b+"\n-----\n",f.scrollTop=f.scrollHeight-f.clientHeight):a||i(b);return true};a.getInternetExplorerMajorVersion=function(){var h=a.getInternetExplorerMajorVersion,f;if(typeof a.getInternetExplorerMajorVersion.cached!=="undefined")f=a.getInternetExplorerMajorVersion.cached;else{f=3;for(var b=
c.createElement("div"),i=b.getElementsByTagName("i");(b.innerHTML="<\!--[if gt IE "+ ++f+"]><i></i><![endif]--\>")&&i[0];);f=f>4?f:false}return h.cached=f};a.isInternetExplorer=function(){return a.isInternetExplorer.cached=typeof a.isInternetExplorer.cached!=="undefined"?a.isInternetExplorer.cached:Boolean(a.getInternetExplorerMajorVersion())};a.emulated={pushState:!Boolean(e.history&&e.history.pushState&&e.history.replaceState&&!(/ Mobile\/([1-7][a-z]|(8([abcde]|f(1[0-8]))))/i.test(g.userAgent)||
/AppleWebKit\/5([0-2]|3[0-2])/i.test(g.userAgent))),hashChange:Boolean(!("onhashchange"in e||"onhashchange"in c)||a.isInternetExplorer()&&a.getInternetExplorerMajorVersion()<8)};a.enabled=!a.emulated.pushState;a.bugs={setHash:Boolean(!a.emulated.pushState&&g.vendor==="Apple Computer, Inc."&&/AppleWebKit\/5([0-2]|3[0-3])/.test(g.userAgent)),safariPoll:Boolean(!a.emulated.pushState&&g.vendor==="Apple Computer, Inc."&&/AppleWebKit\/5([0-2]|3[0-3])/.test(g.userAgent)),ieDoubleCheck:Boolean(a.isInternetExplorer()&&
a.getInternetExplorerMajorVersion()<8),hashEscape:Boolean(a.isInternetExplorer()&&a.getInternetExplorerMajorVersion()<7)};a.isEmptyObject=function(a){for(var f in a)return false;return true};a.cloneObject=function(a){a?(a=m.stringify(a),a=m.parse(a)):a={};return a};a.getRootUrl=function(){var a=c.location.protocol+"//"+(c.location.hostname||c.location.host);c.location.port&&(a+=":"+c.location.port);a+="/";return a};a.getBaseHref=function(){var a=c.getElementsByTagName("base"),f=null,f="";a.length===
1&&(f=a[0],f=f.href.replace(/[^\/]+$/,""));(f=f.replace(/\/+$/,""))&&(f+="/");return f};a.getBaseUrl=function(){return a.getBaseHref()||a.getBasePageUrl()||a.getRootUrl()};a.getPageUrl=function(){return((a.getState(false,false)||{}).url||c.location.href).replace(/\/+$/,"").replace(/[^\/]+$/,function(a){return/\./.test(a)?a:a+"/"})};a.getBasePageUrl=function(){return c.location.href.replace(/[#\?].*/,"").replace(/[^\/]+$/,function(a){return/[^\/]$/.test(a)?"":a}).replace(/\/+$/,"")+"/"};a.getFullUrl=
function(h,f){var b=h,c=h.substring(0,1),f=typeof f==="undefined"?true:f;/[a-z]+\:\/\//.test(h)||(b=c==="/"?a.getRootUrl()+h.replace(/^\/+/,""):c==="#"?a.getPageUrl().replace(/#.*/,"")+h:c==="?"?a.getPageUrl().replace(/[\?#].*/,"")+h:f?a.getBaseUrl()+h.replace(/^(\.\/)+/,""):a.getBasePageUrl()+h.replace(/^(\.\/)+/,""));return b.replace(/\#$/,"")};a.getShortUrl=function(h){var f=a.getBaseUrl(),b=a.getRootUrl();a.emulated.pushState&&(h=h.replace(f,""));h=h.replace(b,"/");a.isTraditionalAnchor(h)&&(h=
"./"+h);return h=h.replace(/^(\.\/)+/g,"./").replace(/\#$/,"")};a.store={};a.idToState=a.idToState||{};a.stateToId=a.stateToId||{};a.urlToId=a.urlToId||{};a.storedStates=a.storedStates||[];a.savedStates=a.savedStates||[];a.normalizeStore=function(){a.store.idToState=a.store.idToState||{};a.store.urlToId=a.store.urlToId||{};a.store.stateToId=a.store.stateToId||{}};a.getState=function(h,f){typeof h==="undefined"&&(h=true);typeof f==="undefined"&&(f=true);var b=a.getLastSavedState();!b&&f&&(b=a.createStateObject());
if(h)b=a.cloneObject(b),b.url=b.cleanUrl||b.url;return b};a.getIdByState=function(h){var f=a.extractId(h.url),b;if(!f)if(b=a.getStateString(h),typeof a.stateToId[b]!=="undefined")f=a.stateToId[b];else if(typeof a.store.stateToId[b]!=="undefined")f=a.store.stateToId[b];else{for(;;)if(f=(new Date).getTime()+String(Math.random()).replace(/\D/g,""),typeof a.idToState[f]==="undefined"&&typeof a.store.idToState[f]==="undefined")break;a.stateToId[b]=f;a.idToState[f]=h}return f};a.normalizeState=function(h){var b;
if(!h||typeof h!=="object")h={};if(typeof h.normalized!=="undefined")return h;if(!h.data||typeof h.data!=="object")h.data={};b={normalized:true};b.title=h.title||"";b.url=a.getFullUrl(a.unescapeString(h.url||c.location.href));b.hash=a.getShortUrl(b.url);b.data=a.cloneObject(h.data);b.id=a.getIdByState(b);b.cleanUrl=b.url.replace(/\??\&_suid.*/,"");b.url=b.cleanUrl;h=!a.isEmptyObject(b.data);if(b.title||h)b.hash=a.getShortUrl(b.url).replace(/\??\&_suid.*/,""),/\?/.test(b.hash)||(b.hash+="?"),b.hash+=
"&_suid="+b.id;b.hashedUrl=a.getFullUrl(b.hash);if((a.emulated.pushState||a.bugs.safariPoll)&&a.hasUrlDuplicate(b))b.url=b.hashedUrl;return b};a.createStateObject=function(h,b,c){h={data:h,title:b,url:c};return h=a.normalizeState(h)};a.getStateById=function(h){h=String(h);return a.idToState[h]||a.store.idToState[h]||b};a.getStateString=function(h){h={data:a.normalizeState(h).data,title:h.title,url:h.url};return m.stringify(h)};a.getStateId=function(h){return a.normalizeState(h).id};a.getHashByState=
function(h){return a.normalizeState(h).hash};a.extractId=function(a){return((a=/(.*)\&_suid=([0-9]+)$/.exec(a))?String(a[2]||""):"")||false};a.isTraditionalAnchor=function(a){return!/[\/\?\.]/.test(a)};a.extractState=function(b,f){var c=null,i,d,f=f||false;(i=a.extractId(b))&&(c=a.getStateById(i));c||(d=a.getFullUrl(b),(i=a.getIdByUrl(d)||false)&&(c=a.getStateById(i)),!c&&f&&!a.isTraditionalAnchor(b)&&(c=a.createStateObject(null,null,d)));return c};a.getIdByUrl=function(h){return a.urlToId[h]||a.store.urlToId[h]||
b};a.getLastSavedState=function(){return a.savedStates[a.savedStates.length-1]||b};a.getLastStoredState=function(){return a.storedStates[a.storedStates.length-1]||b};a.hasUrlDuplicate=function(b){var f=false;return f=(f=a.extractState(b.url))&&f.id!==b.id};a.storeState=function(b){a.urlToId[b.url]=b.id;a.storedStates.push(a.cloneObject(b));return b};a.isLastSavedState=function(b){var f=false;if(a.savedStates.length)b=b.id,f=a.getLastSavedState(),f=f.id,f=b===f;return f};a.saveState=function(b){if(a.isLastSavedState(b))return false;
a.savedStates.push(a.cloneObject(b));return true};a.getStateByIndex=function(b){var f=null;return f=typeof b==="undefined"?a.savedStates[a.savedStates.length-1]:b<0?a.savedStates[a.savedStates.length+b]:a.savedStates[b]};a.getHash=function(){return a.unescapeHash(c.location.hash)};a.unescapeString=function(a){for(var b;;){b=e.unescape(a);if(b===a)break;a=b}return a};a.unescapeHash=function(b){b=a.normalizeHash(b);return b=a.unescapeString(b)};a.normalizeHash=function(a){return a.replace(/[^#]*#/,
"").replace(/#.*/,"")};a.setHash=function(b,f){var i,d;if(f!==false&&a.busy())return a.pushQueue({scope:a,callback:a.setHash,args:arguments,queue:f}),false;i=a.escapeHash(b);a.busy(true);if((d=a.extractState(b,true))&&!a.emulated.pushState)a.pushState(d.data,d.title,d.url,false);else if(c.location.hash!==i)a.bugs.setHash?(d=a.getPageUrl(),a.pushState(null,null,d+"#"+i,false)):c.location.hash=i;return a};a.escapeHash=function(b){b=a.normalizeHash(b);b=e.escape(b);a.bugs.hashEscape||(b=b.replace(/\%21/g,
"!").replace(/\%26/g,"&").replace(/\%3D/g,"=").replace(/\%3F/g,"?"));return b};a.getHashByUrl=function(b){b=String(b).replace(/([^#]*)#?([^#]*)#?(.*)/,"$2");return b=a.unescapeHash(b)};a.setTitle=function(b){var f=b.title,i;f||(i=a.getStateByIndex(0))&&i.url===b.url&&(f=i.title||a.options.initialTitle);try{c.getElementsByTagName("title")[0].innerHTML=f.replace("<","&lt;").replace(">","&gt;").replace(" & "," &amp; ")}catch(d){}c.title=f;return a};a.queues=[];a.busy=function(b){if(typeof b!=="undefined")a.busy.flag=
b;else if(typeof a.busy.flag==="undefined")a.busy.flag=false;if(!a.busy.flag){o(a.busy.timeout);var f=function(){var b,h;if(!a.busy.flag)for(b=a.queues.length-1;b>=0;--b)if(h=a.queues[b],h.length!==0)h=h.shift(),a.fireQueueItem(h),a.busy.timeout=k(f,a.options.busyDelay)};a.busy.timeout=k(f,a.options.busyDelay)}return a.busy.flag};a.busy.flag=false;a.fireQueueItem=function(b){return b.callback.apply(b.scope||a,b.args||[])};a.pushQueue=function(b){a.queues[b.queue||0]=a.queues[b.queue||0]||[];a.queues[b.queue||
0].push(b);return a};a.queue=function(b,f){typeof b==="function"&&(b={callback:b});if(typeof f!=="undefined")b.queue=f;a.busy()?a.pushQueue(b):a.fireQueueItem(b);return a};a.clearQueue=function(){a.busy.flag=false;a.queues=[];return a};a.stateChanged=false;a.doubleChecker=false;a.doubleCheckComplete=function(){a.stateChanged=true;a.doubleCheckClear();return a};a.doubleCheckClear=function(){if(a.doubleChecker)o(a.doubleChecker),a.doubleChecker=false;return a};a.doubleCheck=function(b){a.stateChanged=
false;a.doubleCheckClear();if(a.bugs.ieDoubleCheck)a.doubleChecker=k(function(){a.doubleCheckClear();a.stateChanged||b();return true},a.options.doubleCheckInterval);return a};a.safariStatePoll=function(){var b=a.extractState(c.location.href);if(!a.isLastSavedState(b))return b||a.createStateObject(),a.Adapter.trigger(e,"popstate"),a};a.back=function(b){if(b!==false&&a.busy())return a.pushQueue({scope:a,callback:a.back,args:arguments,queue:b}),false;a.busy(true);a.doubleCheck(function(){a.back(false)});
l.go(-1);return true};a.forward=function(b){if(b!==false&&a.busy())return a.pushQueue({scope:a,callback:a.forward,args:arguments,queue:b}),false;a.busy(true);a.doubleCheck(function(){a.forward(false)});l.go(1);return true};a.go=function(b,f){var c;if(b>0)for(c=1;c<=b;++c)a.forward(f);else if(b<0)for(c=-1;c>=b;--c)a.back(f);else throw Error("History.go: History.go requires a positive or negative integer passed.");return a};if(a.emulated.pushState){var n=function(){};a.pushState=a.pushState||n;a.replaceState=
a.replaceState||n}else a.onPopState=function(b,f){var i=false,i=false;a.doubleCheckComplete();if(i=a.getHash())return(i=a.extractState(i||c.location.href,true))?a.replaceState(i.data,i.title,i.url,false):(a.Adapter.trigger(e,"anchorchange"),a.busy(false)),a.expectedStateId=false;(i=(i=a.Adapter.extractEventData("state",b,f)||false)?a.getStateById(i):a.expectedStateId?a.getStateById(a.expectedStateId):a.extractState(c.location.href))||(i=a.createStateObject(null,null,c.location.href));a.expectedStateId=
false;if(a.isLastSavedState(i))return a.busy(false),false;a.storeState(i);a.saveState(i);a.setTitle(i);a.Adapter.trigger(e,"statechange");a.busy(false);return true},a.Adapter.bind(e,"popstate",a.onPopState),a.pushState=function(b,f,i,c){if(a.getHashByUrl(i)&&a.emulated.pushState)throw Error("History.js does not support states with fragement-identifiers (hashes/anchors).");if(c!==false&&a.busy())return a.pushQueue({scope:a,callback:a.pushState,args:arguments,queue:c}),false;a.busy(true);var d=a.createStateObject(b,
f,i);a.isLastSavedState(d)?a.busy(false):(a.storeState(d),a.expectedStateId=d.id,l.pushState(d.id,d.title,d.url),a.Adapter.trigger(e,"popstate"));return true},a.replaceState=function(b,f,i,c){if(a.getHashByUrl(i)&&a.emulated.pushState)throw Error("History.js does not support states with fragement-identifiers (hashes/anchors).");if(c!==false&&a.busy())return a.pushQueue({scope:a,callback:a.replaceState,args:arguments,queue:c}),false;a.busy(true);var d=a.createStateObject(b,f,i);a.isLastSavedState(d)?
a.busy(false):(a.storeState(d),a.expectedStateId=d.id,l.replaceState(d.id,d.title,d.url),a.Adapter.trigger(e,"popstate"));return true};if(j)try{a.store=m.parse(j.getItem("History.store"))||{}}catch(t){a.store={}}else a.store={};a.normalizeStore();a.Adapter.bind(e,"beforeunload",a.clearAllIntervals);a.Adapter.bind(e,"unload",a.clearAllIntervals);a.saveState(a.storeState(a.extractState(c.location.href,true)));if(j)a.onUnload=function(){var b,f;try{b=m.parse(j.getItem("History.store"))||{}}catch(i){b=
{}}b.idToState=b.idToState||{};b.urlToId=b.urlToId||{};b.stateToId=b.stateToId||{};for(f in a.idToState)a.idToState.hasOwnProperty(f)&&(b.idToState[f]=a.idToState[f]);for(f in a.urlToId)a.urlToId.hasOwnProperty(f)&&(b.urlToId[f]=a.urlToId[f]);for(f in a.stateToId)a.stateToId.hasOwnProperty(f)&&(b.stateToId[f]=a.stateToId[f]);a.store=b;a.normalizeStore();j.setItem("History.store",m.stringify(b))},a.intervalList.push(q(a.onUnload,a.options.storeInterval)),a.Adapter.bind(e,"beforeunload",a.onUnload),
a.Adapter.bind(e,"unload",a.onUnload);if(!a.emulated.pushState&&(a.bugs.safariPoll&&a.intervalList.push(q(a.safariStatePoll,a.options.safariPollInterval)),g.vendor==="Apple Computer, Inc."||(g.appCodeName||"")==="Mozilla"))if(a.Adapter.bind(e,"hashchange",function(){a.Adapter.trigger(e,"popstate")}),a.getHash())a.Adapter.onDomLoad(function(){a.Adapter.trigger(e,"hashchange")})};a.init()})(window);
(function(e,b,d){function c(a,i){var f=b.createElement(a||"div"),c;for(c in i)f[c]=i[c];return f}function g(a,b,f){f&&!f.parentNode&&g(a,f);a.insertBefore(b,f||null);return a}function j(b,c,f,d){var g=["opacity",c,~~(b*100),f,d].join("-"),f=0.01+f/d*100,d=Math.max(1-(1-b)/c*(100-f),b),e=i.substring(0,i.indexOf("Animation")).toLowerCase();m[g]||(a.insertRule("@"+(e&&"-"+e+"-"||"")+"keyframes "+g+"{0%{opacity:"+d+"}"+f+"%{opacity:"+b+"}"+(f+0.01)+"%{opacity:1}"+(f+c)%100+"%{opacity:"+b+"}100%{opacity:"+
d+"}}",0),m[g]=1);return g}function k(a,b){var f=a.style,i,c;if(f[b]!==d)return b;b=b.charAt(0).toUpperCase()+b.slice(1);for(c=0;c<p.length;c++)if(i=p[c]+b,f[i]!==d)return i}function o(a,b){for(var f in b)a.style[k(a,f)||f]=b[f];return a}function q(a){for(var b={x:a.offsetLeft,y:a.offsetTop};a=a.offsetParent;)b.x+=a.offsetLeft,b.y+=a.offsetTop;return b}var p=["webkit","Moz","ms","O"],m={},i;g(b.getElementsByTagName("head")[0],c("style"));var a=b.styleSheets[b.styleSheets.length-1],l=function h(a){if(!this.spin)return new h(a);
var a=a||{},b={lines:12,length:7,width:5,radius:10,color:"#000",speed:1,trail:100,opacity:0.25,fps:20},i;for(i in b)a[i]===d&&(a[i]=b[i]);this.opts=a},n=l.prototype={spin:function(a){this.stop();var b=this,d=b.el=o(c(),{position:"relative"}),e,l;a&&(l=q(g(a,d,a.firstChild)),e=q(d),o(d,{left:(a.offsetWidth>>1)-e.x+l.x+"px",top:(a.offsetHeight>>1)-e.y+l.y+"px"}));d.setAttribute("aria-role","progressbar");b.lines(d,b.opts);if(!i){var j=b.opts,n=0,k=j.fps,m=k/j.speed,p=(1-j.opacity)/(m*j.trail/100),r=
m/j.lines;(function s(){n++;for(var a=j.lines;a;a--){var i=Math.max(1-(n+a*r)%m*p,j.opacity);b.opacity(d,j.lines-a,i,j)}b.timeout=b.el&&setTimeout(s,~~(1E3/k))})()}return b},stop:function(){var a=this.el;if(a)clearTimeout(this.timeout),a.parentNode&&a.parentNode.removeChild(a),this.el=d;return this}};n.lines=function(a,b){function d(a,i){return o(c(),{position:"absolute",width:b.length+b.width+"px",height:b.width+"px",background:a,boxShadow:i,transformOrigin:"left",transform:"rotate("+~~(360/b.lines*
e)+"deg) translate("+b.radius+"px,0)",borderRadius:(b.width>>1)+"px"})}for(var e=0,l;e<b.lines;e++)l=o(c(),{position:"absolute",top:1+~(b.width/2)+"px",transform:"translate3d(0,0,0)",opacity:b.opacity,animation:i&&j(b.opacity,b.trail,e,b.lines)+" "+1/b.speed+"s linear infinite"}),b.shadow&&g(l,o(d("#000","0 0 4px #000"),{top:"2px"})),g(a,g(l,d(b.color,"0 0 1px rgba(0,0,0,.1)")));return a};n.opacity=function(a,b,i){if(b<a.childNodes.length)a.childNodes[b].style.opacity=i};(function(){var b=o(c("group"),
{behavior:"url(#default#VML)"});if(!k(b,"transform")&&b.adj){for(b=4;b--;)a.addRule(["group","roundrect","fill","stroke"][b],"behavior:url(#default#VML)");n.lines=function(a,b){function i(){return o(c("group",{coordsize:h+" "+h,coordorigin:-e+" "+-e}),{width:h,height:h})}function d(a,f,h){g(l,g(o(i(),{rotation:360/b.lines*a+"deg",left:~~f}),g(o(c("roundrect",{arcsize:1}),{width:e,height:b.width,left:b.radius,top:-b.width>>1,filter:h}),c("fill",{color:b.color,opacity:b.opacity}),c("stroke",{opacity:0}))))}
var e=b.length+b.width,h=2*e,l=i(),j=~(b.length+b.radius+b.width)+"px",n;if(b.shadow)for(n=1;n<=b.lines;n++)d(n,-2,"progid:DXImageTransform.Microsoft.Blur(pixelradius=2,makeshadow=1,shadowopacity=.3)");for(n=1;n<=b.lines;n++)d(n);return g(o(a,{margin:j+" 0 0 "+j,zoom:1}),l)};n.opacity=function(a,b,i,c){var h;var f;a=a.firstChild;c=c.shadow&&c.lines||0;if(a&&b+c<a.childNodes.length&&(h=(f=(a=a.childNodes[b+c])&&a.firstChild,a=f)&&a.firstChild,a=h))a.opacity=i}}else i=k(b,"animation")})();e.Spinner=
l})(window,document);
(function(){function e(b,a){var e;this.element=typeof b=="object"?b:document.getElementById(b);this.wrapper=this.element.parentNode;this.element.style.webkitTransitionProperty="-webkit-transform";this.element.style.webkitTransitionTimingFunction="cubic-bezier(0,0,0.25,1)";this.element.style.webkitTransitionDuration="0";this.element.style.webkitTransform=q+"0,0"+p;this.options={bounce:d,momentum:d,checkDOMChanges:true,topOnDOMChanges:false,hScrollbar:d,vScrollbar:d,fadeScrollbar:c||!g,shrinkScrollbar:c||
!g,desktopCompatibility:false,overflow:"auto",snap:false,bounceLock:false,scrollbarColor:"rgba(0,0,0,0.5)",onScrollEnd:function(){},disableTouchEvents:true};if(typeof a=="object")for(e in a)this.options[e]=a[e];if(this.options.desktopCompatibility)this.options.overflow="hidden";this.onScrollEnd=this.options.onScrollEnd;delete this.options.onScrollEnd;this.wrapper.style.overflow=this.options.overflow;this.refresh();window.addEventListener("onorientationchange"in window?"orientationchange":"resize",
this,false);(g||this.options.desktopCompatibility)&&this.element.addEventListener(j,this,false);this.options.checkDOMChanges&&this.element.addEventListener("DOMSubtreeModified",this,false)}function b(b,a,c,d,g){var e=document;this.dir=b;this.fade=c;this.shrink=d;this.uid=++m;this.bar=e.createElement("div");this.bar.style.cssText="position:absolute;top:0;left:0;-webkit-transition-timing-function:cubic-bezier(0,0,0.25,1);pointer-events:none;-webkit-transition-duration:0;-webkit-transition-delay:0;-webkit-transition-property:-webkit-transform;z-index:10;background:"+
g+";-webkit-transform:"+q+"0,0"+p+";"+(b=="horizontal"?"-webkit-border-radius:3px 2px;min-width:6px;min-height:5px":"-webkit-border-radius:2px 3px;min-width:5px;min-height:6px");this.wrapper=e.createElement("div");this.wrapper.style.cssText="-webkit-mask:-webkit-canvas(scrollbar"+this.uid+this.dir+");position:absolute;z-index:10;pointer-events:none;overflow:hidden;opacity:0;-webkit-transition-duration:"+(c?"300ms":"0")+";-webkit-transition-delay:0;-webkit-transition-property:opacity;"+(this.dir==
"horizontal"?"bottom:2px;left:2px;right:7px;height:5px":"top:2px;right:2px;bottom:7px;width:5px;");this.wrapper.appendChild(this.bar);a.appendChild(this.wrapper)}e.prototype={x:0,y:0,enabled:true,handleEvent:function(b){switch(b.type){case j:this.touchStart(b);break;case k:this.touchMove(b);break;case o:this.touchEnd(b);break;case "webkitTransitionEnd":this.transitionEnd();break;case "orientationchange":case "resize":this.refresh();break;case "DOMSubtreeModified":this.onDOMModified(b)}},onDOMModified:function(b){var a=
this;b.target.parentNode==a.element&&(setTimeout(function(){a.refresh()},0),a.options.topOnDOMChanges&&(a.x!=0||a.y!=0)&&a.scrollTo(0,0,"0"))},refresh:function(){var c=this.x,a=this.y;this.scrollWidth=this.wrapper.clientWidth;this.scrollHeight=this.wrapper.clientHeight;this.scrollerWidth=this.element.offsetWidth;this.scrollerHeight=this.element.offsetHeight;this.maxScrollX=this.scrollWidth-this.scrollerWidth;this.maxScrollY=this.scrollHeight-this.scrollerHeight;this.directionY=this.directionX=0;if(this.scrollX)if(this.maxScrollX>=
0)c=0;else if(this.x<this.maxScrollX)c=this.maxScrollX;if(this.scrollY)if(this.maxScrollY>=0)a=0;else if(this.y<this.maxScrollY)a=this.maxScrollY;if(this.options.snap)this.maxPageX=-Math.floor(this.maxScrollX/this.scrollWidth),this.maxPageY=-Math.floor(this.maxScrollY/this.scrollHeight),a=this.snap(c,a),c=a.x,a=a.y;if(c!=this.x||a!=this.y)this.setTransitionTime("0"),this.setPosition(c,a,true);this.scrollX=this.scrollerWidth>this.scrollWidth;this.scrollY=!this.options.bounceLock&&!this.scrollX||this.scrollerHeight>
this.scrollHeight;if(this.options.hScrollbar&&this.scrollX)this.scrollBarX=this.scrollBarX||new b("horizontal",this.wrapper,this.options.fadeScrollbar,this.options.shrinkScrollbar,this.options.scrollbarColor),this.scrollBarX.init(this.scrollWidth,this.scrollerWidth);else if(this.scrollBarX)this.scrollBarX=this.scrollBarX.remove();if(this.options.vScrollbar&&this.scrollY&&this.scrollerHeight>this.scrollHeight)this.scrollBarY=this.scrollBarY||new b("vertical",this.wrapper,this.options.fadeScrollbar,
this.options.shrinkScrollbar,this.options.scrollbarColor),this.scrollBarY.init(this.scrollHeight,this.scrollerHeight);else if(this.scrollBarY)this.scrollBarY=this.scrollBarY.remove()},setPosition:function(b,a,c){this.x=b;this.y=a;this.element.style.webkitTransform=q+this.x+"px,"+this.y+"px"+p;c||(this.scrollBarX&&this.scrollBarX.setPosition(this.x),this.scrollBarY&&this.scrollBarY.setPosition(this.y))},setTransitionTime:function(b){b=b||"0";this.element.style.webkitTransitionDuration=b;if(this.scrollBarX)this.scrollBarX.bar.style.webkitTransitionDuration=
b,this.scrollBarX.wrapper.style.webkitTransitionDuration=d&&this.options.fadeScrollbar?"300ms":"0";if(this.scrollBarY)this.scrollBarY.bar.style.webkitTransitionDuration=b,this.scrollBarY.wrapper.style.webkitTransitionDuration=d&&this.options.fadeScrollbar?"300ms":"0"},touchStart:function(b){var a;if(this.enabled){this.options.disableTouchEvents&&b.preventDefault();b.stopPropagation();this.scrolling=true;this.moved=false;this.distY=this.distX=0;this.setTransitionTime("0");if(this.options.momentum||
this.options.snap)if(a=new WebKitCSSMatrix(window.getComputedStyle(this.element).webkitTransform),a.e!=this.x||a.f!=this.y)document.removeEventListener("webkitTransitionEnd",this,false),this.setPosition(a.e,a.f),this.moved=true;this.touchStartX=g?b.changedTouches[0].pageX:b.pageX;this.scrollStartX=this.x;this.touchStartY=g?b.changedTouches[0].pageY:b.pageY;this.scrollStartY=this.y;this.scrollStartTime=b.timeStamp;this.directionY=this.directionX=0;this.element.addEventListener(k,this,false);this.element.addEventListener(o,
this,false)}},touchMove:function(b){if(this.scrolling){var a=g?b.changedTouches[0].pageX:b.pageX,c=g?b.changedTouches[0].pageY:b.pageY,d=this.scrollX?a-this.touchStartX:0,e=this.scrollY?c-this.touchStartY:0,h=this.x+d,f=this.y+e;b.stopPropagation();this.touchStartX=a;this.touchStartY=c;if(h>=0||h<this.maxScrollX)h=this.options.bounce?Math.round(this.x+d/3):h>=0||this.maxScrollX>=0?0:this.maxScrollX;if(f>=0||f<this.maxScrollY)f=this.options.bounce?Math.round(this.y+e/3):f>=0||this.maxScrollY>=0?0:
this.maxScrollY;if(this.distX+this.distY>40){b.preventDefault();b.stopPropagation();if(this.distX-3>this.distY)f=this.y,e=0;else if(this.distY-3>this.distX)h=this.x,d=0;this.setPosition(h,f);this.moved=true;this.directionX=d>0?-1:1;this.directionY=e>0?-1:1}else this.distX+=Math.abs(d),this.distY+=Math.abs(e)}},touchEnd:function(b){if(this.scrolling){var a=b.timeStamp-this.scrollStartTime,c=g?b.changedTouches[0]:b,d,b=0;d=this.x;var e=this.y;this.scrolling=false;if(this.moved)if(!this.options.snap&&
a>250)this.resetPosition();else{this.options.momentum&&(d=this.scrollX===true?this.momentum(this.x-this.scrollStartX,a,this.options.bounce?-this.x+this.scrollWidth/5:-this.x,this.options.bounce?this.x+this.scrollerWidth-this.scrollWidth+this.scrollWidth/5:this.x+this.scrollerWidth-this.scrollWidth):{dist:0,time:0},a=this.scrollY===true?this.momentum(this.y-this.scrollStartY,a,this.options.bounce?-this.y+this.scrollHeight/5:-this.y,this.options.bounce?(this.maxScrollY<0?this.y+this.scrollerHeight-
this.scrollHeight:0)+this.scrollHeight/5:this.y+this.scrollerHeight-this.scrollHeight):{dist:0,time:0},b=Math.max(Math.max(d.time,a.time),1),d=this.x+d.dist,e=this.y+a.dist);if(this.options.snap)a=this.snap(d,e),d=a.x,e=a.y,b=Math.max(a.time,b);this.scrollTo(d,e,b+"ms")}else if(this.resetPosition(),g)for(b=c.target;b.nodeType!=1;)b=b.parentNode}},transitionEnd:function(){document.removeEventListener("webkitTransitionEnd",this,false);this.resetPosition()},resetPosition:function(){var b=this.x,a=this.y;
if(this.x>=0)b=0;else if(this.x<this.maxScrollX)b=this.maxScrollX;if(this.y>=0||this.maxScrollY>0)a=0;else if(this.y<this.maxScrollY)a=this.maxScrollY;if(b!=this.x||a!=this.y)this.scrollTo(b,a);else{if(this.moved)this.onScrollEnd(),this.moved=false;this.scrollBarX&&this.scrollBarX.hide();this.scrollBarY&&this.scrollBarY.hide()}},snap:function(b,a){var c,b=this.directionX>0?Math.floor(b/this.scrollWidth):this.directionX<0?Math.ceil(b/this.scrollWidth):Math.round(b/this.scrollWidth);this.pageX=-b;b*=
this.scrollWidth;if(b>0)b=this.pageX=0;else if(b<this.maxScrollX)this.pageX=this.maxPageX,b=this.maxScrollX;a=this.directionY>0?Math.floor(a/this.scrollHeight):this.directionY<0?Math.ceil(a/this.scrollHeight):Math.round(a/this.scrollHeight);this.pageY=-a;a*=this.scrollHeight;if(a>0)a=this.pageY=0;else if(a<this.maxScrollY)this.pageY=this.maxPageY,a=this.maxScrollY;c=Math.round(Math.max(Math.abs(this.x-b)/this.scrollWidth*500,Math.abs(this.y-a)/this.scrollHeight*500));return{x:b,y:a,time:c}},scrollTo:function(b,
a,c){this.x==b&&this.y==a?this.resetPosition():(this.moved=true,this.setTransitionTime(c||"350ms"),this.setPosition(b,a),c==="0"||c=="0s"||c=="0ms"?this.resetPosition():document.addEventListener("webkitTransitionEnd",this,false))},scrollToPage:function(b,a,c){if(!this.options.snap)this.pageX=-Math.round(this.x/this.scrollWidth),this.pageY=-Math.round(this.y/this.scrollHeight);b=="next"?b=++this.pageX:b=="prev"&&(b=--this.pageX);a=="next"?a=++this.pageY:a=="prev"&&(a=--this.pageY);b=-b*this.scrollWidth;
a=-a*this.scrollHeight;a=this.snap(b,a);b=a.x;a=a.y;this.scrollTo(b,a,c||"500ms")},scrollToElement:function(b,a){if(b=typeof b=="object"?b:this.element.querySelector(b)){var c=this.scrollX?-b.offsetLeft:0,d=this.scrollY?-b.offsetTop:0;if(c>=0)c=0;else if(c<this.maxScrollX)c=this.maxScrollX;if(d>=0)d=0;else if(d<this.maxScrollY)d=this.maxScrollY;this.scrollTo(c,d,a)}},momentum:function(b,a,c,d){var a=Math.abs(b)/a*1E3,e=a*a/2.5/1E3,g=0;b>0&&e>c?(a=a*c/e/2.5,e=c):b<0&&e>d&&(a=a*d/e/2.5,e=d);e*=b<0?
-1:1;g=a/1.2;return{dist:Math.round(e),time:Math.round(g)}},destroy:function(b){window.removeEventListener("onorientationchange"in window?"orientationchange":"resize",this,false);this.element.removeEventListener(j,this,false);this.element.removeEventListener(k,this,false);this.element.removeEventListener(o,this,false);document.removeEventListener("webkitTransitionEnd",this,false);this.options.checkDOMChanges&&this.element.removeEventListener("DOMSubtreeModified",this,false);if(this.scrollBarX)this.scrollBarX=
this.scrollBarX.remove();if(this.scrollBarY)this.scrollBarY=this.scrollBarY.remove();b&&this.wrapper.parentNode.removeChild(this.wrapper);return null}};b.prototype={init:function(b,a){var c=document,d=Math.PI;if(this.dir=="horizontal"){if(this.maxSize!=this.wrapper.offsetWidth)this.maxSize=this.wrapper.offsetWidth,c=c.getCSSCanvasContext("2d","scrollbar"+this.uid+this.dir,this.maxSize,5),c.fillStyle="rgb(0,0,0)",c.beginPath(),c.arc(2.5,2.5,2.5,d/2,-d/2,false),c.lineTo(this.maxSize-2.5,0),c.arc(this.maxSize-
2.5,2.5,2.5,-d/2,d/2,false),c.closePath(),c.fill()}else if(this.maxSize!=this.wrapper.offsetHeight)this.maxSize=this.wrapper.offsetHeight,c=c.getCSSCanvasContext("2d","scrollbar"+this.uid+this.dir,5,this.maxSize),c.fillStyle="rgb(0,0,0)",c.beginPath(),c.arc(2.5,2.5,2.5,d,0,false),c.lineTo(5,this.maxSize-2.5),c.arc(2.5,this.maxSize-2.5,2.5,0,d,false),c.closePath(),c.fill();this.size=Math.max(Math.round(this.maxSize*this.maxSize/a),6);this.maxScroll=this.maxSize-this.size;this.toWrapperProp=this.maxScroll/
(b-a);this.bar.style[this.dir=="horizontal"?"width":"height"]=this.size+"px"},setPosition:function(b){this.wrapper.style.opacity!="1"&&this.show();b=Math.round(this.toWrapperProp*b);b<0?(b=this.shrink?b+b*3:0,this.size+b<7&&(b=-this.size+6)):b>this.maxScroll&&(b=this.shrink?b+(b-this.maxScroll)*3:this.maxScroll,this.size+this.maxScroll-b<7&&(b=this.size+this.maxScroll-6));b=this.dir=="horizontal"?q+b+"px,0"+p:q+"0,"+b+"px"+p;this.bar.style.webkitTransform=b},show:function(){if(d)this.wrapper.style.webkitTransitionDelay=
"0";this.wrapper.style.opacity="1"},hide:function(){if(d)this.wrapper.style.webkitTransitionDelay="350ms";this.wrapper.style.opacity="0"},remove:function(){this.wrapper.parentNode.removeChild(this.wrapper);return null}};var d="WebKitCSSMatrix"in window&&"m11"in new WebKitCSSMatrix,c=/iphone|ipad/gi.test(navigator.appVersion),g="ontouchstart"in window,j=g?"touchstart":"mousedown",k=g?"touchmove":"mousemove",o=g?"touchend":"mouseup",q="translate"+(d?"3d(":"("),p=d?",0)":")",m=0;window.iScroll=e})();